name: CodeQL Analysis

on:
  push:
    branches: [main]

jobs:
  analyze:
    name: Analyze PHP code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: php
      - name: Build CodeQL database
        uses: github/codeql-action/analyze@v2
        with:
          query: query.ql
          languages: php
      - name: Upload CodeQL results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeql-results.sarif
